---
apiVersion: v1
kind: Pod
metadata:
  name: prober
  labels:
    name: prober
spec:
  containers:
    - name: prober
      image: nullmethod/prober:latest
      ports:
        - containerPort: 6379
